import './globals.css';

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by Next.js',
};



import Providers from './Providers';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
